Change id to username in users list and change the url
pixelfed/pixelfed pull request #122
Opened 2018-06-01 19:56 UTC by Whaxion

All in the title, solve my issue #119

2018-06-01 21:03 UTC, andriussev requested changes
1. Why not leave the id column?

2. This introduces more complexity to number of database calls since the profile load will happen for each user separately.
This brings it to a total of a `O(1+3*n)` database calls where `n` is the number of users, on this page.

2018-06-01 21:15 UTC, Whaxion commented
1.
If  don't leave the id column, it's because on mobile, the table was too large.

2. Solved.

2018-06-05 03:29 UTC, merged

2021-02-06 20:44 UTC, dansup commented
@stemy2 Can you check the logs in `storage/logs/laravel.log`, also did you clear the cache and run post-deployment commands?

2021-02-06 22:56 UTC, stemy2 commented
Here's a link to the log: https://lufi.stemy.me/r/xuDmuy5wDC#KHzNr3dJs5VVkC3Rmt2kD4KXUIw6o9tt79WwKJ+iNuA=

I can't copypaste the content because it's too heavy.

Clear the cache fixed nothing.

The post-deployment commands had been run.

2021-02-07 01:31 UTC, dansup commented
@stemy2 Looks like the `pgsql` php extension is not installed or enabled in `php.ini`.

2021-02-07 01:37 UTC, stemy2 commented
Indeed, it was not installed and installing it fixed my problem. I still wonder why the extension had disappeard.