Add character limit info
pixelfed/pixelfed pull request #127
Opened 2018-06-01 20:55 UTC by m4sk1n

#121

2018-06-01 21:23 UTC, andriussev requested changes
Will be a pain in the ass if the validation changes. Should be moved to the configuration and parsed from there to both the message and the validation rule.

Also, should return old data if limit failed (as should other fields). Limits should also be enforced with HTML.

2018-06-01 22:14 UTC, dansup commented
@m4sk1n I will be adding a character limit in the pixelfed config so that admins can set their own limit. It will require some additional logic in the view, controller and configs

2018-06-05 03:35 UTC, dansup commented
@m4sk1n @andriussev This was merged in #150 with configurable limit.

2018-06-05 03:35 UTC, closed without merging

2021-02-05 12:37 UTC, mnowiasz commented
I found the issue - was a wrong setting in php's conf: 8MB max upload size vs 15MB allowed in Pixelfed. It would be much easier to find such problems if php errors would be logged.