Update PostComponent.vue
pixelfed/pixelfed pull request #2424
Opened 2020-10-21 21:05 UTC by okpierre

Allow word to wrap instead of breaking up

https://github.com/pixelfed/pixelfed/issues/2423#issue-726860576

Before
![pixelfedcomment-before](https://user-images.githubusercontent.com/1679025/96787250-6a6ad680-13bf-11eb-9e27-dfc0baea953f.png)

After
![pixelfedcomment-after](https://user-images.githubusercontent.com/1679025/96787260-6ccd3080-13bf-11eb-94f1-da1a162b7ef2.png)

2020-11-03 16:31 UTC, hiidemo submitted a review, later dismissed

2020-11-13 00:17 UTC, justinharkey submitted a review, later dismissed
LGTM

2020-11-20 10:46 UTC, tripu approved these changes

2020-11-20 10:53 UTC, tripu commented
I was just about to submit an identical PR, good thing that I found this before :slightly_smiling_face:

2020-11-20 10:57 UTC, tripu requested changes
L[mostly]GTM.

Two issues, though:

1. Shouldn't this PR go against `pixelfed:staging`?
1. Shouldn't this remove also the same `word-break` CSS rule from these other two lines: [184](https://github.com/pixelfed/pixelfed/blob/staging/resources/assets/js/components/PostComponent.vue#L184), [207](https://github.com/pixelfed/pixelfed/blob/staging/resources/assets/js/components/PostComponent.vue#L207)?

2020-12-13 15:36 UTC, tripu commented
@dansup&hellip;?

2020-12-13 23:40 UTC, dansup approved these changes

2020-12-13 23:40 UTC, merged

2020-12-14 11:41 UTC, tripu commented
:tada: