Workable Docker container definitions and docker-compose runtime
pixelfed/pixelfed pull request #38
Opened 2018-05-29 08:40 UTC by moritzheiber

These are a couple of changes that are (IMHO) necessary to get Pixelfed running as an isolated Docker container:

### Dockerfile
- Pin the PHP version in the dependent Docker `FROM` target. Otherwise we might get into trouble when there are version updates
- Pin the `composer` version and install it from its official source, including a checksum verification to ensure we aren't installing malicious code
- Pre-populate a slew of needed directories inside the image (you can still use a `bind` mount to overwrite them) to ensure the Docker image is able to run without having an sources mounted into the image
- Use `www-data` as the user which owns the storage directory structure.

### docker-compose.yml

You will need to run the following two commands in order to get the stack to run:

```
$ cp .env.example .env
$ docker-compose run --rm php php artisan key:generate --show
```
Save the output somewhere and then run the following command:

```
$ APP_KEY="<the-output>" docker-compose up
```

After a short while the application should be available at [http://localhost:3000](http://localhost:3000).

I would've written a README section for this, but I was unsure what the plans were in terms of documentation.

2018-05-29 09:25 UTC, kpcyrd requested changes
hey, thanks for your help! There are some things that might need attention, mostly to ensure the application is harder to exploit and enforce immutability inside the container. :)

2018-05-29 09:25 UTC, kpcyrd commented on Dockerfile
> +    /var/www/html/pixelfed/storage \
We can't set those permissions at buildtime, if we mount a directory to this location it's going to be owned by root with default permissions. We might have to wrap around the php entrypoint to initialize those at runtime.

2018-05-29 09:25 UTC, kpcyrd commented on Dockerfile
> +COPY --chown=www-data . /var/www/html/pixelfed/
The application should not be able to modify itself. Directories that need to be writable should be set to writable explicitly.

2018-05-29 09:25 UTC, kpcyrd commented on Dockerfile
> +VOLUME ["/var/www/html"]
This is going to make `/var/www/html` an empty folder when used outside of docker-compose. This should point to the `storage/` folder instead.

2018-05-29 09:25 UTC, kpcyrd commented on docker-compose-running.yml
> +---
The original file was super barebones to get started, feel free to merge all of your changes into one file. :)

2018-05-29 09:25 UTC, kpcyrd commented on docker-compose.yml
> +      - APP_KEY=${APP_KEY:-app_key}
This key is used internally for security stuff and must not have a default value.

2018-05-29 09:25 UTC, kpcyrd commented on Dockerfile
> +WORKDIR /var/www/html/pixelfed
If the webroot changes, the nginx.conf has to be edited as well.

2018-05-29 09:25 UTC, kpcyrd commented on Dockerfile
> +USER www-data
The dependencies are explicitly installed as root to prevent the application from editing them.

2018-05-29 10:23 UTC, moritzheiber commented on Dockerfile
> +    /var/www/html/pixelfed/storage \
I'm not sure what you're implying here, could you clarify?

2018-05-29 10:23 UTC, moritzheiber commented on Dockerfile
> +COPY --chown=www-data . /var/www/html/pixelfed/
Do we know which those are?

2018-05-29 10:24 UTC, moritzheiber commented on Dockerfile
> +VOLUME ["/var/www/html"]
No, if you're using named volumes (which should be the case for pretty much anyone considering the run Docker in a non-dev environment) the folder content is going to be a part of the volume (see the `docker-compose-running.yml` file for an example).

2018-05-29 10:25 UTC, moritzheiber commented on docker-compose-running.yml
> +---
The issue here is: These files serve two different purposes. One of them has you run the containers against your development environment, the other is used to run the Docker container in a setup where the development environment is no longer required. Merging these two files wouldn't work.

2018-05-29 10:25 UTC, moritzheiber commented on docker-compose.yml
> +      - APP_KEY=${APP_KEY:-app_key}
It's not going to work anyway, since the app expects it to be a base64 encoded CBC-128/256 cipher. I'll remove it.

2018-05-29 10:27 UTC, moritzheiber commented on Dockerfile
> +USER www-data
Maybe we can use a user different from `root` instead then? I mean, composer literally says "Don't run me as root"?

2018-05-29 10:27 UTC, moritzheiber commented on Dockerfile
> +WORKDIR /var/www/html/pixelfed
Yup, I was planning on submitting a second PR to include a shoe-in nginx configuration afterwards

2018-05-30 14:42 UTC, kpcyrd commented on Dockerfile
> +    /var/www/html/pixelfed/storage \
`docker run -v /foo:/var/www/html/pixelfed/storage ...` is probably a common thing to be done, if `/foo` doesn't exist on the host system yet, docker is going to create it with root:root as owner and 0755 as mode. This means that the folder is empty and www-data can't write to it, unless we change the owner inside the entrypoint script. This is very common in the official docker images.

2018-05-30 14:42 UTC, kpcyrd commented on Dockerfile
> +COPY --chown=www-data . /var/www/html/pixelfed/
That should be `/var/www/html/pixelfed/storage` only, maybe @dansup can help? :)

2018-05-30 14:50 UTC, kpcyrd commented on Dockerfile
> +USER www-data
We could install the dependencies as www-data and then chown all files to root afterwards. I'm pretty sure they mean "don't run composer as root on your host system" :) The risk of running composer as root in docker containers is neglectable unless you're worried about kernel 0days.

2018-05-30 14:52 UTC, kpcyrd commented on Dockerfile
> +VOLUME ["/var/www/html"]
oh, I didn't know that. I think bind-mounting folders into the image is still a common thing to do (I'm doing this to reduce complexity of my setup).

2018-05-30 15:14 UTC, moritzheiber commented on Dockerfile
> +VOLUME ["/var/www/html"]
None that I would be aware of. We've been using the same principle with application that need to exposed to a CGI handler ever since named volumes became "a thing".

2018-05-30 15:15 UTC, moritzheiber commented on Dockerfile
> +USER www-data
Sounds good, I'll amend the PR.

2018-05-30 15:15 UTC, moritzheiber commented on Dockerfile
> +COPY --chown=www-data . /var/www/html/pixelfed/
I think it's at least the directories I'm trying to create earlier.. ?

2018-05-30 15:19 UTC, moritzheiber commented on Dockerfile
> +    /var/www/html/pixelfed/storage \
Ah, now I know what you're getting at. That's true for host bind mounts, but not for named volumes. In fact, the owner/group and access permissions are vital on already created directories inside the container to make sure the volumes are getting the same set of rules assigned to them.

In essence, I think this is a problem that amounts to "host mounts" v. "named volumes" ..

2018-05-31 19:45 UTC, moritzheiber commented
@kpcyrd I tried incorporating most of your suggestions. Could you take a look again?

2018-06-02 16:59 UTC, kpcyrd approved these changes

2018-06-03 01:34 UTC, merged