internationalization of site/about, site/fediverse, site/opensource
pixelfed/pixelfed pull request #5389
Opened 2024-12-09 17:31 UTC by nesges

Added new keys for language used in blades and added them in resources/lang/en/site.php with the original text and resources/lang/de/site.php with a german translation

2024-12-10 00:54 UTC, x64x2 approved these changes

2024-12-14 02:46 UTC, x64x2 approved these changes

2025-01-04 03:31 UTC, dansup requested changes
Please fix the merge conflict!

2025-01-04 09:30 UTC, nesges commented
fixed

2025-01-05 21:37 UTC, dansup submitted a review, later dismissed

2025-01-05 21:39 UTC, dansup approved these changes

2025-01-05 21:40 UTC, dansup commented
@nesges Nice work, thanks!

2025-01-05 21:40 UTC, merged