fixed a bash scripting bug in start.sh
pixelfed/pixelfed pull request #553
Opened 2018-11-12 19:24 UTC by koehn

that prevented horizon from ever starting.

2018-11-14 00:30 UTC, dereckson requested changes
Keep = operator, add quotes.

2018-11-14 00:30 UTC, dereckson commented on contrib/docker/start.sh
> +if [ "$HORIZON_EMBED" -eq "true" ]; then
-eq is for integers, = is well the comparison operator to use for strings.

The real bug was the lack of "" (and that should be fixed).

2018-11-25 21:00 UTC, dansup requested changes
Fix merge conflict

2018-11-25 21:17 UTC, koehn commented
Changes merged.

2018-11-26 19:54 UTC, dansup approved these changes

2018-11-26 19:55 UTC, merged