Add required PHP extensions to composer.json
pixelfed/pixelfed pull request #701
Opened 2018-12-27 17:49 UTC by mattsches

Signed-off-by: Matthias Gutjahr <mattsches@gmail.com>

2019-01-06 06:49 UTC, dansup requested changes

2019-01-06 06:49 UTC, dansup commented on composer.json
> +        "ext-redis": "*",
Please remove this. It will conflict with the default redis library pixelfed uses.

```suggestion
```

2019-01-07 09:34 UTC, mattsches commented
Used the Github GUI to "commit suggestion", not sure what's supposed to happen next ;)

2019-01-23 20:59 UTC, dansup approved these changes

2019-01-23 20:59 UTC, merged